version: "3"
services:
  postgres:
    image: registry.cn-hangzhou.aliyuncs.com/k8ops/postgres:11-alpine
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: dFr88uKVBsyZk
    restart: unless-stopped
    volumes:
      - /data/oes/data/sonarqube/postgres:/var/lib/postgresql/data

  sonar:
    image: registry.cn-hangzhou.aliyuncs.com/k8ops/sonarqube:8.9.0-community
    depends_on:
      - postgres
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: dFr88uKVBsyZk
      SONAR_WEB_JAVAADDITIONALOPTS: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.3.jar=web"
      SONAR_CE_JAVAADDITIONALOPTS: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.3.jar=ce"
    ports:
      - 9000:9000
    volumes:
      - /data/oes/data/sonarqube/conf:/opt/sonarqube/conf
      - /data/oes/data/sonarqube/data:/opt/sonarqube/data
      - ./extensions:/opt/sonarqube/extensions
    restart: unless-stopped

networks:
  default:
    external:
      name: oes-network
